# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node-based build and test

on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm run sass
      - run: npm test
        continue-on-error: true

      - name: upload test results
        uses: actions/upload-artifact@v3
        with:
          name: backstop.js report
          path: backstop_data

